name: Build, Push (GHCR) and Deploy (Swarm)

on:
  push:
    branches: [ "main" ]
    paths:
      - "apps/app/**"
      - "apps/api/**"
      - ".github/workflows/build-deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_APP: ghcr.io/tadeubdev/infra-swarm-app
  IMAGE_API: ghcr.io/tadeubdev/infra-swarm-api

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push APP
        uses: docker/build-push-action@v6
        with:
          context: ./apps/app
          push: true
          tags: |
            ${{ env.IMAGE_APP }}:latest
            ${{ env.IMAGE_APP }}:${{ github.sha }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: |
            ${{ env.IMAGE_API }}:latest
            ${{ env.IMAGE_API }}:${{ github.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Swarm manager via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e

            echo "Deploying SHA: ${{ github.sha }}"

            docker service update --with-registry-auth \
              --image ${{ env.IMAGE_APP }}:${{ github.sha }} \
              apps_app

            docker service update --with-registry-auth \
              --image ${{ env.IMAGE_API }}:${{ github.sha }} \
              apps_api

            docker service ls | grep -E 'apps_app|apps_api' || true

      - name: Telegram Success
        if: success()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=✅ Deploy concluído App e API atualizados para SHA: ${{ github.sha }}"

      - name: Telegram Failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=❌ Deploy falhou Verifique o workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
